# Generated by Django 4.2.16 on 2024-11-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='bike_type',
            field=models.CharField(blank=True, choices=[('mountain', 'Mountain Bike'), ('road', 'Road Bike'), ('city', 'City Bike'), ('kids', 'Kids Bike')], default='mountain', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='specs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
