# Generated by Django 4.2.16 on 2024-12-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_bike_city_bike_color_bike_features_bike_frame_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('needs_repair', 'Needs Repair')], default='new', max_length=50),
        ),
        migrations.AddField(
            model_name='bike',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
