# Generated by Django 4.2.16 on 2024-12-03 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_bike_condition_bike_model_bike_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='category',
        ),
        migrations.AddField(
            model_name='bike',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
