# Generated by Django 4.2.16 on 2024-12-10 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0007_alter_order_options_order_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Shipping addresses',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='bike',
            name='frame_material',
            field=models.CharField(blank=True, choices=[('aluminum', 'Aluminum'), ('carbon', 'Carbon'), ('steel', 'Steel'), ('titanium', 'Titanium'), ('chromoly', 'Chromoly')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('reserved', 'Reserved'), ('hidden', 'Hidden')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='bike_type',
            field=models.CharField(blank=True, choices=[('mountain', 'Mountain Bike'), ('road', 'Road Bike'), ('city', 'City Bike'), ('hybrid', 'Hybrid Bike'), ('cruiser', 'Cruiser Bike'), ('bmx', 'BMX Bike'), ('electric', 'Electric Bike'), ('folding', 'Folding Bike'), ('touring', 'Touring Bike'), ('gravel', 'Gravel Bike'), ('cyclocross', 'Cyclocross Bike'), ('kids', 'Kids Bike'), ('fat', 'Fat Bike'), ('track', 'Track/Fixed Gear')], default='mountain', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='frame_size',
            field=models.CharField(blank=True, choices=[('xs', 'XS (13-14")'), ('s', 'S (15-16")'), ('m', 'M (17-18")'), ('l', 'L (19-20")'), ('xl', 'XL (21-22")')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='wheel_size',
            field=models.CharField(blank=True, choices=[('12', '12"'), ('16', '16"'), ('20', '20"'), ('24', '24"'), ('26', '26"'), ('27.5', '27.5"'), ('29', '29"'), ('700c', '700c')], max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='bike',
            index=models.Index(fields=['bike_type'], name='products_bi_bike_ty_be5023_idx'),
        ),
        migrations.AddIndex(
            model_name='bike',
            index=models.Index(fields=['status'], name='products_bi_status_5f7cec_idx'),
        ),
        migrations.AddIndex(
            model_name='bike',
            index=models.Index(fields=['created_at'], name='products_bi_created_187d38_idx'),
        ),
        migrations.AddIndex(
            model_name='bike',
            index=models.Index(fields=['price'], name='products_bi_price_e58811_idx'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.shippingaddress'),
        ),
    ]
