# Generated by Django 4.2.16 on 2024-12-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_shippingaddress_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='state',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used')], db_index=True, default='new', help_text='Whether the bike is new or used', max_length=10),
        ),
        migrations.AlterField(
            model_name='bike',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('needs_repair', 'Needs Repair')], default='new', help_text='Detailed condition of the bike', max_length=50),
        ),
        migrations.AddIndex(
            model_name='bike',
            index=models.Index(fields=['state'], name='products_bi_state_3bbc0a_idx'),
        ),
    ]
