# Generated by Django 4.2.16 on 2025-01-03 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
