# Generated by Django 4.2.16 on 2025-01-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('category', models.CharField(choices=[('mountain', 'Mountain Bikes'), ('road', 'Road Bikes'), ('city', 'City Bikes')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='bike',
            name='products_bi_bike_ty_be5023_idx',
        ),
        migrations.RemoveIndex(
            model_name='bike',
            name='products_bi_status_5f7cec_idx',
        ),
        migrations.RemoveIndex(
            model_name='bike',
            name='products_bi_created_187d38_idx',
        ),
        migrations.RemoveIndex(
            model_name='bike',
            name='products_bi_price_e58811_idx',
        ),
        migrations.RemoveIndex(
            model_name='bike',
            name='products_bi_state_3bbc0a_idx',
        ),
        migrations.AddIndex(
            model_name='bike',
            index=models.Index(fields=['name'], name='products_bi_name_f52c89_idx'),
        ),
        migrations.AddIndex(
            model_name='bike',
            index=models.Index(fields=['brand'], name='products_bi_brand_6981a5_idx'),
        ),
        migrations.AddIndex(
            model_name='bike',
            index=models.Index(fields=['model'], name='products_bi_model_ed91b2_idx'),
        ),
        migrations.AddIndex(
            model_name='bike',
            index=models.Index(fields=['city'], name='products_bi_city_c8a568_idx'),
        ),
    ]
