# Generated by Django 4.2.16 on 2025-01-16 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_message_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bikes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bike_images', to='products.bike')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
