# Generated by Django 4.2.16 on 2025-01-17 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_bikeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikeimage',
            name='bike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.bike'),
        ),
    ]
