# Generated by Django 4.2.16 on 2025-01-31 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_bike_slug_alter_bike_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bikeimage',
            options={'ordering': ['created_at'], 'verbose_name': 'Bike Image', 'verbose_name_plural': 'Bike Images'},
        ),
        migrations.AlterField(
            model_name='bikeimage',
            name='bike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='products.bike'),
        ),
        migrations.AlterField(
            model_name='bikeimage',
            name='image',
            field=models.ImageField(upload_to='bikes/', verbose_name='Additional Image'),
        ),
    ]
