export const cities = [
  { value: "acre", label: "Acre (עכו)" },
  { value: "afula", label: "Afula (עפולה)" },
  { value: "ashdod", label: "Ashdod (אשדוד)" },
  { value: "ashkelon", label: "Ashkelon (אשקלון)" },
  { value: "bat_yam", label: "Bat Yam (בת ים)" },
  { value: "beer_sheva", label: "Be'er Sheva (באר שבע)" },
  { value: "bnei_brak", label: "Bnei Brak (בני ברק)" },
  { value: "carmiel", label: "Carmiel (כרמיאל)" },
  { value: "dimona", label: "Dimona (דימונה)" },
  { value: "eilat", label: "Eilat (אילת)" },
  { value: "givataim", label: "Givataim (גבעתיים)" },
  { value: "hadera", label: "Hadera (חדרה)" },
  { value: "haifa", label: "Haifa (חיפה)" },
  { value: "herzliya", label: "Herzliya (הרצליה)" },
  { value: "hod_hasharon", label: "Hod HaSharon (הוד השרון)" },
  { value: "holon", label: "Holon (חולון)" },
  { value: "jerusalem", label: "Jerusalem (ירושלים)" },
  { value: "kfar_saba", label: "Kfar Saba (כפר סבא)" },
  { value: "kiryat_ata", label: "Kiryat Ata (קרית אתא)" },
  { value: "kiryat_bialik", label: "Kiryat Bialik (קרית ביאליק)" },
  { value: "kiryat_gat", label: "Kiryat Gat (קרית גת)" },
  { value: "kiryat_motzkin", label: "Kiryat Motzkin (קרית מוצקין)" },
  { value: "kiryat_yam", label: "Kiryat Yam (קרית ים)" },
  { value: "lod", label: "Lod (לוד)" },
  { value: "modiin", label: "Modi'in (מודיעין)" },
  { value: "nahariya", label: "Nahariya (נהריה)" },
  { value: "nazareth", label: "Nazareth (נצרת)" },
  { value: "netanya", label: "Netanya (נתניה)" },
  { value: "or_yehuda", label: "Or Yehuda (אור יהודה)" },
  { value: "petah_tikva", label: "Petah Tikva (פתח תקווה)" },
  { value: "raanana", label: "Ra'anana (רעננה)" },
  { value: "ramat_gan", label: "Ramat Gan (רמת גן)" },
  { value: "ramat_hasharon", label: "Ramat HaSharon (רמת השרון)" },
  { value: "ramla", label: "Ramla (רמלה)" },
  { value: "rehovot", label: "Rehovot (רחובות)" },
  { value: "rishon_lezion", label: "Rishon LeZion (ראשון לציון)" },
  { value: "sderot", label: "Sderot (שדרות)" },
  { value: "tel_aviv", label: "Tel Aviv (תל אביב)" },
  { value: "tiberias", label: "Tiberias (טבריה)" },
  { value: "yavne", label: "Yavne (יבנה)" },
];
